// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cars.sql

package sqlc

import (
	"context"

	"github.com/shopspring/decimal"
)

type BulkInsertCarImagesParams struct {
	Url   string
	CarID *int64
}

const createCar = `-- name: CreateCar :one
INSERT INTO cars (new, brand, model, year, price, color, km, description)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, new, brand, model, year, price, color, km, description
`

type CreateCarParams struct {
	New         bool
	Brand       string
	Model       string
	Year        int32
	Price       decimal.Decimal
	Color       string
	Km          int32
	Description string
}

func (q *Queries) CreateCar(ctx context.Context, arg CreateCarParams) (Car, error) {
	row := q.db.QueryRow(ctx, createCar,
		arg.New,
		arg.Brand,
		arg.Model,
		arg.Year,
		arg.Price,
		arg.Color,
		arg.Km,
		arg.Description,
	)
	var i Car
	err := row.Scan(
		&i.ID,
		&i.New,
		&i.Brand,
		&i.Model,
		&i.Year,
		&i.Price,
		&i.Color,
		&i.Km,
		&i.Description,
	)
	return i, err
}

const deleteCar = `-- name: DeleteCar :execrows
DELETE FROM cars WHERE id = $1
`

func (q *Queries) DeleteCar(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCar, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCarImagesByCarID = `-- name: DeleteCarImagesByCarID :exec
DELETE FROM car_images WHERE car_id = $1
`

func (q *Queries) DeleteCarImagesByCarID(ctx context.Context, carID *int64) error {
	_, err := q.db.Exec(ctx, deleteCarImagesByCarID, carID)
	return err
}

const getCar = `-- name: GetCar :one
SELECT id, new, brand, model, year, price, color, km, description FROM cars WHERE id = $1
`

func (q *Queries) GetCar(ctx context.Context, id int64) (Car, error) {
	row := q.db.QueryRow(ctx, getCar, id)
	var i Car
	err := row.Scan(
		&i.ID,
		&i.New,
		&i.Brand,
		&i.Model,
		&i.Year,
		&i.Price,
		&i.Color,
		&i.Km,
		&i.Description,
	)
	return i, err
}

const listCarImagesByCarIDs = `-- name: ListCarImagesByCarIDs :many
SELECT id, url, car_id FROM car_images WHERE car_id = ANY($1::bigint[]) ORDER BY id
`

func (q *Queries) ListCarImagesByCarIDs(ctx context.Context, dollar_1 []int64) ([]CarImage, error) {
	rows, err := q.db.Query(ctx, listCarImagesByCarIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CarImage{}
	for rows.Next() {
		var i CarImage
		if err := rows.Scan(&i.ID, &i.Url, &i.CarID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCars = `-- name: ListCars :many
SELECT id, new, brand, model, year, price, color, km, description FROM cars ORDER BY id
`

func (q *Queries) ListCars(ctx context.Context) ([]Car, error) {
	rows, err := q.db.Query(ctx, listCars)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Car{}
	for rows.Next() {
		var i Car
		if err := rows.Scan(
			&i.ID,
			&i.New,
			&i.Brand,
			&i.Model,
			&i.Year,
			&i.Price,
			&i.Color,
			&i.Km,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCar = `-- name: UpdateCar :one
UPDATE cars
SET new         = $2,
    brand       = $3,
    model       = $4,
    year        = $5,
    price       = $6,
    color       = $7,
    km          = $8,
    description = $9
WHERE id = $1
RETURNING id, new, brand, model, year, price, color, km, description
`

type UpdateCarParams struct {
	ID          int64
	New         bool
	Brand       string
	Model       string
	Year        int32
	Price       decimal.Decimal
	Color       string
	Km          int32
	Description string
}

func (q *Queries) UpdateCar(ctx context.Context, arg UpdateCarParams) (Car, error) {
	row := q.db.QueryRow(ctx, updateCar,
		arg.ID,
		arg.New,
		arg.Brand,
		arg.Model,
		arg.Year,
		arg.Price,
		arg.Color,
		arg.Km,
		arg.Description,
	)
	var i Car
	err := row.Scan(
		&i.ID,
		&i.New,
		&i.Brand,
		&i.Model,
		&i.Year,
		&i.Price,
		&i.Color,
		&i.Km,
		&i.Description,
	)
	return i, err
}

const updateCarImage = `-- name: UpdateCarImage :exec
UPDATE car_images SET url = $2 WHERE id = $1 AND car_id = $3
`

type UpdateCarImageParams struct {
	ID    int64
	Url   string
	CarID *int64
}

func (q *Queries) UpdateCarImage(ctx context.Context, arg UpdateCarImageParams) error {
	_, err := q.db.Exec(ctx, updateCarImage, arg.ID, arg.Url, arg.CarID)
	return err
}
