// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comissions.sql

package sqlc

import (
	"context"

	"github.com/shopspring/decimal"
)

const createComission = `-- name: CreateComission :one
INSERT INTO vendor_comissions (
    vendor_id, vendor_name, comission_percentage, comission_amount, order_id, order_total
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, vendor_id, vendor_name, comission_percentage, comission_amount, order_id, order_total
`

type CreateComissionParams struct {
	VendorID            int64
	VendorName          string
	ComissionPercentage decimal.Decimal
	ComissionAmount     decimal.Decimal
	OrderID             int64
	OrderTotal          decimal.Decimal
}

func (q *Queries) CreateComission(ctx context.Context, arg CreateComissionParams) (VendorComission, error) {
	row := q.db.QueryRow(ctx, createComission,
		arg.VendorID,
		arg.VendorName,
		arg.ComissionPercentage,
		arg.ComissionAmount,
		arg.OrderID,
		arg.OrderTotal,
	)
	var i VendorComission
	err := row.Scan(
		&i.ID,
		&i.VendorID,
		&i.VendorName,
		&i.ComissionPercentage,
		&i.ComissionAmount,
		&i.OrderID,
		&i.OrderTotal,
	)
	return i, err
}

const deleteComission = `-- name: DeleteComission :execrows
DELETE FROM vendor_comissions WHERE id = $1
`

func (q *Queries) DeleteComission(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteComission, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getComission = `-- name: GetComission :one
SELECT id, vendor_id, vendor_name, comission_percentage, comission_amount, order_id, order_total FROM vendor_comissions WHERE id = $1
`

func (q *Queries) GetComission(ctx context.Context, id int64) (VendorComission, error) {
	row := q.db.QueryRow(ctx, getComission, id)
	var i VendorComission
	err := row.Scan(
		&i.ID,
		&i.VendorID,
		&i.VendorName,
		&i.ComissionPercentage,
		&i.ComissionAmount,
		&i.OrderID,
		&i.OrderTotal,
	)
	return i, err
}

const listComissions = `-- name: ListComissions :many
SELECT id, vendor_id, vendor_name, comission_percentage, comission_amount, order_id, order_total FROM vendor_comissions ORDER BY id
`

func (q *Queries) ListComissions(ctx context.Context) ([]VendorComission, error) {
	rows, err := q.db.Query(ctx, listComissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VendorComission{}
	for rows.Next() {
		var i VendorComission
		if err := rows.Scan(
			&i.ID,
			&i.VendorID,
			&i.VendorName,
			&i.ComissionPercentage,
			&i.ComissionAmount,
			&i.OrderID,
			&i.OrderTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComissionsByVendor = `-- name: ListComissionsByVendor :many
SELECT id, vendor_id, vendor_name, comission_percentage, comission_amount, order_id, order_total FROM vendor_comissions WHERE vendor_id = $1 ORDER BY id
`

func (q *Queries) ListComissionsByVendor(ctx context.Context, vendorID int64) ([]VendorComission, error) {
	rows, err := q.db.Query(ctx, listComissionsByVendor, vendorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VendorComission{}
	for rows.Next() {
		var i VendorComission
		if err := rows.Scan(
			&i.ID,
			&i.VendorID,
			&i.VendorName,
			&i.ComissionPercentage,
			&i.ComissionAmount,
			&i.OrderID,
			&i.OrderTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateComission = `-- name: UpdateComission :one
UPDATE vendor_comissions
SET vendor_id            = $2,
    vendor_name          = $3,
    comission_percentage = $4,
    comission_amount     = $5,
    order_id             = $6,
    order_total          = $7
WHERE id = $1
RETURNING id, vendor_id, vendor_name, comission_percentage, comission_amount, order_id, order_total
`

type UpdateComissionParams struct {
	ID                  int64
	VendorID            int64
	VendorName          string
	ComissionPercentage decimal.Decimal
	ComissionAmount     decimal.Decimal
	OrderID             int64
	OrderTotal          decimal.Decimal
}

func (q *Queries) UpdateComission(ctx context.Context, arg UpdateComissionParams) (VendorComission, error) {
	row := q.db.QueryRow(ctx, updateComission,
		arg.ID,
		arg.VendorID,
		arg.VendorName,
		arg.ComissionPercentage,
		arg.ComissionAmount,
		arg.OrderID,
		arg.OrderTotal,
	)
	var i VendorComission
	err := row.Scan(
		&i.ID,
		&i.VendorID,
		&i.VendorName,
		&i.ComissionPercentage,
		&i.ComissionAmount,
		&i.OrderID,
		&i.OrderTotal,
	)
	return i, err
}

const upsertComissionByOrder = `-- name: UpsertComissionByOrder :one
INSERT INTO vendor_comissions (
    vendor_id, vendor_name, comission_percentage, comission_amount, order_id, order_total
)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (order_id) DO UPDATE
SET vendor_id            = EXCLUDED.vendor_id,
    vendor_name          = EXCLUDED.vendor_name,
    comission_percentage = EXCLUDED.comission_percentage,
    comission_amount     = EXCLUDED.comission_amount,
    order_total          = EXCLUDED.order_total
RETURNING id, vendor_id, vendor_name, comission_percentage, comission_amount, order_id, order_total
`

type UpsertComissionByOrderParams struct {
	VendorID            int64
	VendorName          string
	ComissionPercentage decimal.Decimal
	ComissionAmount     decimal.Decimal
	OrderID             int64
	OrderTotal          decimal.Decimal
}

func (q *Queries) UpsertComissionByOrder(ctx context.Context, arg UpsertComissionByOrderParams) (VendorComission, error) {
	row := q.db.QueryRow(ctx, upsertComissionByOrder,
		arg.VendorID,
		arg.VendorName,
		arg.ComissionPercentage,
		arg.ComissionAmount,
		arg.OrderID,
		arg.OrderTotal,
	)
	var i VendorComission
	err := row.Scan(
		&i.ID,
		&i.VendorID,
		&i.VendorName,
		&i.ComissionPercentage,
		&i.ComissionAmount,
		&i.OrderID,
		&i.OrderTotal,
	)
	return i, err
}
