// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package sqlc

import (
	"context"
)

// iteratorForBulkInsertCarImages implements pgx.CopyFromSource.
type iteratorForBulkInsertCarImages struct {
	rows                 []BulkInsertCarImagesParams
	skippedFirstNextCall bool
}

func (r *iteratorForBulkInsertCarImages) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBulkInsertCarImages) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Url,
		r.rows[0].CarID,
	}, nil
}

func (r iteratorForBulkInsertCarImages) Err() error {
	return nil
}

func (q *Queries) BulkInsertCarImages(ctx context.Context, arg []BulkInsertCarImagesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"car_images"}, []string{"url", "car_id"}, &iteratorForBulkInsertCarImages{rows: arg})
}

// iteratorForBulkInsertOrderItems implements pgx.CopyFromSource.
type iteratorForBulkInsertOrderItems struct {
	rows                 []BulkInsertOrderItemsParams
	skippedFirstNextCall bool
}

func (r *iteratorForBulkInsertOrderItems) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBulkInsertOrderItems) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].OrderID,
		r.rows[0].CarID,
		r.rows[0].Price,
		r.rows[0].Discount,
	}, nil
}

func (r iteratorForBulkInsertOrderItems) Err() error {
	return nil
}

func (q *Queries) BulkInsertOrderItems(ctx context.Context, arg []BulkInsertOrderItemsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"order_items"}, []string{"order_id", "car_id", "price", "discount"}, &iteratorForBulkInsertOrderItems{rows: arg})
}
