// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type Car struct {
	ID          int64
	New         bool
	Brand       string
	Model       string
	Year        int32
	Price       decimal.Decimal
	Color       string
	Km          int32
	Description string
}

type CarImage struct {
	ID    int64
	Url   string
	CarID *int64
}

type Order struct {
	ID           int64
	CustomerName string
	OrderDate    pgtype.Timestamptz
	Total        decimal.Decimal
	VendorID     int64
}

type OrderItem struct {
	ID       int64
	OrderID  int64
	CarID    int64
	Price    decimal.Decimal
	Discount decimal.Decimal
}

type User struct {
	ID                        int64
	Username                  string
	Password                  string
	Email                     string
	ComissionPerSaleInPercent *int16
	Role                      string
}

type VendorComission struct {
	ID                  int64
	VendorID            int64
	VendorName          string
	ComissionPercentage decimal.Decimal
	ComissionAmount     decimal.Decimal
	OrderID             int64
	OrderTotal          decimal.Decimal
}
