// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type BulkInsertOrderItemsParams struct {
	OrderID  int64
	CarID    int64
	Price    decimal.Decimal
	Discount decimal.Decimal
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (customer_name, order_date, total, vendor_id)
VALUES ($1, $2, $3, $4)
RETURNING id, customer_name, order_date, total, vendor_id
`

type CreateOrderParams struct {
	CustomerName string
	OrderDate    pgtype.Timestamptz
	Total        decimal.Decimal
	VendorID     int64
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.CustomerName,
		arg.OrderDate,
		arg.Total,
		arg.VendorID,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerName,
		&i.OrderDate,
		&i.Total,
		&i.VendorID,
	)
	return i, err
}

const deleteOrder = `-- name: DeleteOrder :execrows
DELETE FROM orders WHERE id = $1
`

func (q *Queries) DeleteOrder(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOrder, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOrderItemsByOrderID = `-- name: DeleteOrderItemsByOrderID :exec
DELETE FROM order_items WHERE order_id = $1
`

func (q *Queries) DeleteOrderItemsByOrderID(ctx context.Context, orderID int64) error {
	_, err := q.db.Exec(ctx, deleteOrderItemsByOrderID, orderID)
	return err
}

const getOrder = `-- name: GetOrder :one
SELECT id, customer_name, order_date, total, vendor_id FROM orders WHERE id = $1
`

func (q *Queries) GetOrder(ctx context.Context, id int64) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerName,
		&i.OrderDate,
		&i.Total,
		&i.VendorID,
	)
	return i, err
}

const listOrderItemsByOrderIDs = `-- name: ListOrderItemsByOrderIDs :many
SELECT id, order_id, car_id, price, discount FROM order_items WHERE order_id = ANY($1::bigint[]) ORDER BY id
`

func (q *Queries) ListOrderItemsByOrderIDs(ctx context.Context, dollar_1 []int64) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, listOrderItemsByOrderIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderItem{}
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.CarID,
			&i.Price,
			&i.Discount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrders = `-- name: ListOrders :many
SELECT id, customer_name, order_date, total, vendor_id FROM orders ORDER BY id
`

func (q *Queries) ListOrders(ctx context.Context) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.CustomerName,
			&i.OrderDate,
			&i.Total,
			&i.VendorID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByVendor = `-- name: ListOrdersByVendor :many
SELECT id, customer_name, order_date, total, vendor_id FROM orders WHERE vendor_id = $1 ORDER BY id
`

func (q *Queries) ListOrdersByVendor(ctx context.Context, vendorID int64) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByVendor, vendorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.CustomerName,
			&i.OrderDate,
			&i.Total,
			&i.VendorID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrder = `-- name: UpdateOrder :one
UPDATE orders
SET customer_name = $2,
    order_date    = $3,
    total         = $4,
    vendor_id     = $5
WHERE id = $1
RETURNING id, customer_name, order_date, total, vendor_id
`

type UpdateOrderParams struct {
	ID           int64
	CustomerName string
	OrderDate    pgtype.Timestamptz
	Total        decimal.Decimal
	VendorID     int64
}

func (q *Queries) UpdateOrder(ctx context.Context, arg UpdateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrder,
		arg.ID,
		arg.CustomerName,
		arg.OrderDate,
		arg.Total,
		arg.VendorID,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerName,
		&i.OrderDate,
		&i.Total,
		&i.VendorID,
	)
	return i, err
}

const updateOrderItem = `-- name: UpdateOrderItem :exec
UPDATE order_items
SET car_id = $2, price = $3, discount = $4
WHERE id = $1 AND order_id = $5
`

type UpdateOrderItemParams struct {
	ID       int64
	CarID    int64
	Price    decimal.Decimal
	Discount decimal.Decimal
	OrderID  int64
}

func (q *Queries) UpdateOrderItem(ctx context.Context, arg UpdateOrderItemParams) error {
	_, err := q.db.Exec(ctx, updateOrderItem,
		arg.ID,
		arg.CarID,
		arg.Price,
		arg.Discount,
		arg.OrderID,
	)
	return err
}
