// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	BulkInsertCarImages(ctx context.Context, arg []BulkInsertCarImagesParams) (int64, error)
	BulkInsertOrderItems(ctx context.Context, arg []BulkInsertOrderItemsParams) (int64, error)
	CreateCar(ctx context.Context, arg CreateCarParams) (Car, error)
	CreateComission(ctx context.Context, arg CreateComissionParams) (VendorComission, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCar(ctx context.Context, id int64) (int64, error)
	DeleteCarImagesByCarID(ctx context.Context, carID *int64) error
	DeleteComission(ctx context.Context, id int64) (int64, error)
	DeleteOrder(ctx context.Context, id int64) (int64, error)
	DeleteOrderItemsByOrderID(ctx context.Context, orderID int64) error
	DeleteUser(ctx context.Context, id int64) (int64, error)
	GetCar(ctx context.Context, id int64) (Car, error)
	GetComission(ctx context.Context, id int64) (VendorComission, error)
	GetOrder(ctx context.Context, id int64) (Order, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListCarImagesByCarIDs(ctx context.Context, dollar_1 []int64) ([]CarImage, error)
	ListCars(ctx context.Context) ([]Car, error)
	ListComissions(ctx context.Context) ([]VendorComission, error)
	ListComissionsByVendor(ctx context.Context, vendorID int64) ([]VendorComission, error)
	ListOrderItemsByOrderIDs(ctx context.Context, dollar_1 []int64) ([]OrderItem, error)
	ListOrders(ctx context.Context) ([]Order, error)
	ListOrdersByVendor(ctx context.Context, vendorID int64) ([]Order, error)
	ListUsers(ctx context.Context) ([]User, error)
	SeedAdmin(ctx context.Context, arg SeedAdminParams) error
	UpdateCar(ctx context.Context, arg UpdateCarParams) (Car, error)
	UpdateCarImage(ctx context.Context, arg UpdateCarImageParams) error
	UpdateComission(ctx context.Context, arg UpdateComissionParams) (VendorComission, error)
	UpdateOrder(ctx context.Context, arg UpdateOrderParams) (Order, error)
	UpdateOrderItem(ctx context.Context, arg UpdateOrderItemParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpsertComissionByOrder(ctx context.Context, arg UpsertComissionByOrderParams) (VendorComission, error)
}

var _ Querier = (*Queries)(nil)
