// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password, email, comission_per_sale_in_percent, role)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, username, password, email, comission_per_sale_in_percent, role
`

type CreateUserParams struct {
	Username                  string
	Password                  string
	Email                     string
	ComissionPerSaleInPercent *int16
	Role                      string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Password,
		arg.Email,
		arg.ComissionPerSaleInPercent,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Email,
		&i.ComissionPerSaleInPercent,
		&i.Role,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password, email, comission_per_sale_in_percent, role FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Email,
		&i.ComissionPerSaleInPercent,
		&i.Role,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password, email, comission_per_sale_in_percent, role FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Email,
		&i.ComissionPerSaleInPercent,
		&i.Role,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, password, email, comission_per_sale_in_percent, role FROM users ORDER BY id
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Password,
			&i.Email,
			&i.ComissionPerSaleInPercent,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seedAdmin = `-- name: SeedAdmin :exec
INSERT INTO users (username, password, email, comission_per_sale_in_percent, role)
VALUES ($1, $2, $3, $4, 'admin')
ON CONFLICT (username) DO NOTHING
`

type SeedAdminParams struct {
	Username                  string
	Password                  string
	Email                     string
	ComissionPerSaleInPercent *int16
}

func (q *Queries) SeedAdmin(ctx context.Context, arg SeedAdminParams) error {
	_, err := q.db.Exec(ctx, seedAdmin,
		arg.Username,
		arg.Password,
		arg.Email,
		arg.ComissionPerSaleInPercent,
	)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET username                      = $2,
    password                      = $3,
    email                         = $4,
    comission_per_sale_in_percent = $5,
    role                          = $6
WHERE id = $1
RETURNING id, username, password, email, comission_per_sale_in_percent, role
`

type UpdateUserParams struct {
	ID                        int64
	Username                  string
	Password                  string
	Email                     string
	ComissionPerSaleInPercent *int16
	Role                      string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Username,
		arg.Password,
		arg.Email,
		arg.ComissionPerSaleInPercent,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Email,
		&i.ComissionPerSaleInPercent,
		&i.Role,
	)
	return i, err
}
